config/routes.rb
Rails.application.routes.draw do
  devise_for :utilisateurs
  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "unlike", to: "articles#downvote"
    end
  end
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  belongs_to :utilisateur
  belongs_to :category
  friendly_id :titre, use: :slugged
  mount_uploader :image, ImageUploader
  acts_as_votable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_utilisateur!, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      @articles = Article.paginate(page: params[:page], per_page: 3)
    else
      @category_id = Category.find_by(nom: params[:category]).id
      @articles = Article.where(category_id: @category_id).order("created_at DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.friendly.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = current_utilisateur.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  def upvote
    @article.upvote_by current_utilisateur
    redirect_to @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_utilisateur.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "L'article a été créé avec succès." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "L'article a été mis à jour avec succès." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "L'article a été détruit avec succès." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:titre, :contenu, :image, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class=" content p-3">
  <%= simple_form_for @article, url: article do |f| %>
    <%= f.error_notification %>
    <%= f.collection_select :category_id, Category.all, :id, :nom,{ promt: 'Choisir une Catégorie'}, class: "mb-2 form-control w-25" %>
    <%= f.input :titre %>
    <%= f.input  :contenu %>
    <%= f.input :image %>
    <%= f.button :submit, class: "btn-outline-secondary rounded-0" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="shadow-sm mb-5 bg-white rounded-0">
  <div class="card-header text-center titre font-weight-bold lead mx-0">Modifier l'article</div>
  <%= render 'form', article: @article %>
  <%= link_to 'Show', @article %> |
  <%= link_to 'Retour', articles_path, class:"p-3" %>
</div>

app/views/articles/index.html.erb
  <%= render 'partials/index'%>

app/views/articles/new.html.erb
<div class="shadow-sm mb-5 bg-white rounded-0">
  <div class="card-header text-center titre font-weight-bold lead mx-0">Nouvel article</div>
  <%= render 'form', article: @article %>
   <%= link_to 'Retour', articles_path, class:"p-3" %>
</div>

app/views/articles/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb rounded-0">
    <%= link_to 'Retour', articles_path,class: "titre" %>
  </ol>
</nav>
<div class="row">
  <div class="col-md-4 img-show">
    <%= image_tag(@article.image_url) %>
  </div>
  <div class="col-md-8">
    <div class="card mb-3 rounded-0">
      <div class="card-body">
        <h5 class="card-title titre font-weight-bold text-decoration-none"> <%= @article.titre %></h5>
        <hr>
        <p class="card-text content"> <%= @article.contenu %>.</p>
      </div>
      <div class="card-footer text-right">
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group titre">
            <%= link_to like_article_path(@article),class: "btn btn-sm btn-outline-secondary rounded-0 content", method: :put do %>
              <span class="glyphicon.glyphicon-heart" aria-hidden="true">Liker
                <%= @article.get_upvotes.size %>
              </span>
              <% end %>
              <% if utilisateur_signed_in? %>
                <%= link_to 'Modifier', edit_article_path(@article),class: "btn btn-sm btn-outline-secondary rounded-0 content" %>
                <%= link_to 'Detruire', @article,class: "btn btn-sm btn-outline-secondary rounded-0 content", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggyblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'partials/header'%>
    <div class="container">
      <% if notice%>
        <div class="alert text-success text-center alert-success rounded-0 content"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert text-danger text-center alert-danger rounded-0 content"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <header class="blog-header py-2 bred col-12 shadow">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4">
          <%= link_to 'bLoGgY', root_path(@article), class:"blog-header-logo text-light font-weight-bold h2" %>
        </div>
        <div class="col-4 text-center">
          <%= link_to 'POSTER UN ARTICLE', new_article_path, class:"btn btn btn-outline-light rounded-0 mr-1 titre font-weight-bold lead" %>
        </div>
        <div class="col-4 d-flex justify-content-end font-weight-bold">
          <% if utilisateur_signed_in? %>
            <%= link_to current_utilisateur.email, edit_utilisateur_registration_path, class:"mr-3" %>
            <%= link_to 'DÉCONNEXION',destroy_utilisateur_session_path, method: :delete, class:"btn btn-sm btn-outline-light rounded-0 mr-1 titre font-weight-bold lead" %>
          <% else %>
            <%= link_to "S'INSCRIRE", new_utilisateur_registration_path, class:"btn btn-sm btn-outline-light rounded-0 mr-1 titre font-weight-bold lead" %>
            <%= link_to "CONNEXION", new_utilisateur_session_path, class:"btn btn-sm btn-outline-light rounded-0 mr-1 titre font-weight-bold lead" %>
          <% end %>
        </div>
      </div>
    </header>
  </div>
</div>
<div class="nav-scroller py-1 mb-3 col-6 offset-3 blight shadow-lg">
  <nav class="nav d-flex justify-content-between titre font-weight-bold">
    <% Category.all.each do |category| %>
      <%= link_to category.nom, articles_path(category: category.nom), class:"mr-3 p-2 text-muted" %>
    <% end %>
  </nav>
</div>

app/views/partials/_index.html.erb
<div class="jumbotron main-header p-4 p-md-5 text-white rounded-0">
  <div class="col-md-6 px-0">
    <h1 class="display-4  titre">Article de cette semaine</h1>
    <p class="lead my-3 content">Disponible depuis le 31 mai, la seconde bêta de la version 2.6 du langage web dynamique Ruby s'enrichit d'un compilateur Just-in-Time, avec à la clef une amélioration des...</p>
    <%= link_to "CONTINUER LA LECTURE", new_utilisateur_session_path, class:"btn btn btn-outline-light  rounded-0 mr-1 titre font-weight-bold lead" %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 blog-main">
    <h3 class="p-3 mb-3 titre font-weight-bold card shadow border-0 rounded-0 text-right bred text-white">
      Vos Articles
    </h3>
    <%= render 'partials/main'%>
    <!-- /.blog-post -->
    <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
  <!-- /.blog-main -->
  <aside class="col-md-4 blight blog-sidebar shadow">
    <div class="p-3 mb-3 rounded-0">
      <h4 class=" titre font-weight-bold">A propos de l'admin</h4>
      <hr>
      <p class="mb-0 lead content">Blog <em>conçu en Ruby on Rails</em>.
        Chaque jour de la semaine à 9h00 HE, nous vous livrerons une nouvelle édition pour bien commencer la journée, ainsi que des éditions de week-end avec quelques-uns des meilleurs films et vidéos de la semaine.</p>
    </div>
    <div class="p-3">
      <h4 class=" titre font-weight-bold">Archives</h4>
      <hr>
      <ol class="list-unstyled mb-0 content">
        <li><a href="">Mars 2019</a></li>
        <li><a href="">Fevrier 2019</a></li>
        <li><a href="">Janvier 2019</a></li>
        <li><a href="">Decembre 2018</a></li>
        <li><a href="">Novembre 2018</a></li>
        <li><a href="">Octobre 2018</a></li>
      </ol>
    </div>
    <div class="p-4">
      <h4 class=" titre font-weight-bold">Sur les RS</h4>
      <hr>
      <ol class="list-unstyled content">
        <li><a href="">GitHub</a></li>
        <li><a href="">Twitter</a></li>
        <li><a href="">Facebook</a></li>
      </ol>
    </div>
  </aside>
  <!-- /.blog-sidebar -->
</div>
<!-- /.row -->

app/views/partials/_main.html.erb
<% @articles.each do |article| %>
  <div class="card mb-4 img-main rounded-0 border-0 shadow">
    <%= image_tag(article.image_url) %>
    <div class="card-body blight ">
      <%= link_to article do %>
        <h5 class="card-title titre font-weight-bold"> <%= article.titre %></h5>
      <% end %>
      <span class="badge alert-info text-muted">Mis à jour, il y a <%= time_ago_in_words(article.created_at) %></span>
      <div class="card-text content text-muted mt-3 ">
        <p><%=  truncate(article.contenu,length: 200) %></p>
      </div>
      <hr>
      <div class="text-right text-dark">
        <span class="p-2 titre font-weight-bold">  posté le : <%= article.created_at.strftime('%d %B %Y')  %></span>
        <br>
        <small class="text-dark titre bagde badge-light rounded-0 p-2 titre"> <i>par </i><%= article.utilisateur.email %>
        </small>
      </div>
    </div>
  </div>
<% end %>